apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transcribealpha
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/transcribealpha:latest
        ports:
        - name: h2c
          containerPort: 8080
        env:
        - name: GEMINI_API_KEY
          value: "your-api-key-here"
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi