# Cloud Build Trigger Configuration
# Use this to set up the trigger manually in Google Cloud Console

name: transcribealpha-auto-deploy
description: Auto-deploy TranscribeAlpha on master push
disabled: false

github:
  owner: nathanjeichert
  name: TranscribeAlpha2.0
  push:
    branch: ^master$

filename: cloudbuild.yaml

substitutions:
  _GEMINI_API_KEY: AIzaSyBzSWIuZdjXtG7A8ibEB2CMiEaQt4EsbjI

# Manual Setup Instructions:
# 1. Go to: https://console.cloud.google.com/cloud-build/triggers
# 2. Click "Create Trigger"
# 3. Select "GitHub (Cloud Build GitHub App)"
# 4. Connect your GitHub account and select "nathanjeichert/TranscribeAlpha2.0" repo
# 5. Configure:
#    - Name: transcribealpha-auto-deploy
#    - Event: Push to a branch
#    - Branch: ^master$
#    - Configuration: Cloud Build configuration file (yaml or json)
#    - Cloud Build configuration file location: cloudbuild.yaml
# 6. Under "Substitution variables", add:
#    - _GEMINI_API_KEY = AIzaSyBzSWIuZdjXtG7A8ibEB2CMiEaQt4EsbjI
# 7. Click "Create"